application: capyoura
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /html
  static_dir: static/html
- url: /images
  static_dir: static/images
- url: /releases
  static_dir: static/releases
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: .*
  script: main.py
